POST http://localhost:8080/signup
Content-Type: application/json

{
    "name":"Long",
    "phone":"0978",
    "email":"klong31122001@gmail.com",
    "password":"123"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"123"
}

###
GET http://localhost:8080/token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjMiLCJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6IjZjbG9tV2p5ck0xbiIsImF2YXRhciI6IiIsImV4cCI6MTY4Mjk1MjczNn0.lZfG41HGZw2mGqz_3w0kUgkRzp8FBGUJzkPjOk4hdBg

###
GET http://localhost:8080/books?page=1

### 
GET http://localhost:8080/books/search?search_text=bjec

###
POST http://localhost:8080/books
Content-Type: application/json

{
   "name":"Giai thuat 5",
   "publisher":"Fahasa",
   "yearpublished": 2020,
   "author":"Tang Kim Long",
   "book_image":"https://example.com/hhgttg.jpg",
   "amount":20,
   "type_id":"2"
}

###
POST http://localhost:8080/books/book_detail/6449d83967b05b84f16cfe38
Content-Type: application/json

{
   "location":"ABC 5"
}


###
GET http://localhost:8080/rentlist

###
GET http://localhost:8080/rentlist/RbPuAnhCPQsw

###
GET http://localhost:8080/books/type?book_type=Manga&page=1

###
GET http://localhost:8080/books/latest

###
GET http://localhost:8080/books/popular

###
GET http://localhost:8080/books/B5

###
GET http://localhost:8080/books/RbPuAnhCPQsw/detail

###
GET http://localhost:8080/borrowlist

###
GET http://localhost:8080/borrowlist/RbPuAnhCPQsw

###
GET http://localhost:8080/history?page=2

###
GET http://localhost:8080/types

###
GET http://localhost:8080/history/6clomWjyrM1n

###
POST http://localhost:8080/rent
Content-Type: application/json

{
    "book_id": "RbPuAnhCPQsw",
    "user_id": "6clomWjyrM1n"
}

###
POST http://localhost:8080/hire
Content-Type: application/json

{
    "book_rent_id": "W5PIUgKAgrnA",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOiJkald6Qk5nRDdDdmMiLCJhdmF0YXIiOiIiLCJleHAiOjE2ODMwMzkyODl9.S1BuxYKfnONxyaEPXwS70QZFa2LEVZWrvD6IJY9s-xI"
}