POST http://localhost:8080/signup
Content-Type: application/json

{
    "name":"Long",
    "phone":"0978",
    "email":"klong31122001@gmail.com",
    "password":"123"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"123"
}

###
GET http://localhost:8080/token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjMiLCJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6IjZjbG9tV2p5ck0xbiIsImF2YXRhciI6IiIsImV4cCI6MTY4Mjk1MjczNn0.lZfG41HGZw2mGqz_3w0kUgkRzp8FBGUJzkPjOk4hdBg

###
GET http://localhost:8080/books?page=1

### 
GET http://localhost:8080/books/search?search_text=bjec

###
POST http://localhost:8080/books
Content-Type: application/json

{
   "name":"Thần Số Học Ứng Dụng",
   "publisher":"Booklife",
   "yearpublished": 2020,
   "author":"Joy Woodward",
   "book_image":"https://salt.tikicdn.com/cache/750x750/ts/product/c8/6f/36/17e0dd709f50c7c7530755e9b21c3865.jpg.webp",
   "amount":0,
   "type_name":"Numerology",
   "page":280,
   "publishing_location":"USA",
   "borrowed_quantity":0,
   "license":"Joy Woodward",
   "description": "Cuốn sách sẽ cung cấp mọi thứ bạn cần để mài giũa trực giác của mình, hiểu rõ hơn những người xung quanh và thậm chí có thêm tự tin khi đưa ra các quyết định lớn.",
    "details":"Truyền thông ngập tràn những khám phá và những lời khuyên mới mẻ về những thứ chúng ta nạp vào cơ thể nhưng có cơ sở khoa học nào cho bất kỳ tuyên bố đó không\nVới những hình minh họa rõ ràng, dễ hiểu, cuốn sách Hiểu hết về thức ăn sẽ mang lại những thông tin lý thú liên quan đến thức ăn, từ công đoạn sản xuất đến ích lợi/tác hại của chúng với sức khỏe."
}

###
POST http://localhost:8080/books/B10
Content-Type: application/json

{
   "location":"ABC 11"
}


###
GET http://localhost:8080/rentlist

###
GET http://localhost:8080/rentlist/RbPuAnhCPQsw

###
GET http://localhost:8080/books/type?book_type=Manga&page=1

###
GET http://localhost:8080/books/newest

###
GET http://localhost:8080/books/popular

###
GET http://localhost:8080/books/B10

###
GET http://localhost:8080/books/B5/detail

###
GET http://localhost:8080/borrowlist

###
GET http://localhost:8080/borrowlist/RbPuAnhCPQsw

###
GET http://localhost:8080/history?page=2

###
GET http://localhost:8080/returnlist

###
GET http://localhost:8080/types

###
GET http://localhost:8080/history/U02

###
POST http://localhost:8080/rent
Content-Type: application/json

{
    "book_id": "B1",
    "user_id": "U02"
}

###
GET http://localhost:8080/rentlist/B10


###
POST http://localhost:8080/hire
Content-Type: application/json

{
    "book_rent_id": "JzicMckNStLj",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOiJVMDEiLCJhdmF0YXIiOiJodHRwczovL2Zhc3RseS5waWNzdW0ucGhvdG9zL2lkLzY3Ni8yMDAvMjAwLmpwZz9obWFjPWhnZU1RRUlLNE1uMjdRMm9MUldqWG8xcmd4d1RiazFDbkpFOTU0aF9IeU0iLCJleHAiOjE2ODMyMDUwOTN9.FmmRTlHnCGm6p8xv4xvoyuApw9Smdw1JkUfipTk4k2E"
}

###
POST http://localhost:8080/return/ROsknkcD1B6w
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOiJVMDEiLCJhdmF0YXIiOiJodHRwczovL2Zhc3RseS5waWNzdW0ucGhvdG9zL2lkLzY3Ni8yMDAvMjAwLmpwZz9obWFjPWhnZU1RRUlLNE1uMjdRMm9MUldqWG8xcmd4d1RiazFDbkpFOTU0aF9IeU0iLCJleHAiOjE2ODMyMDUwOTN9.FmmRTlHnCGm6p8xv4xvoyuApw9Smdw1JkUfipTk4k2E"
}